### PR TITLE
Update SDK to 4.5.1

### PR DESCRIPTION
**Pull request by etharner**

### CODE REVIEW

**Comment by davidyuk** [comment]
`@aeternity/aepp-sdk@4.5.0` released: https://github.com/aeternity/aepp-sdk-js/releases/tag/4.5.0

**Comment by thepiwo** [comment]
@etharner can we update this right to ~4.5.0? when can we have a release of base-aepp with this? (cc @j28 )

**Comment by davidyuk** [comment]
@etharner example app by default should propose to connect to https://base.aepps.com instead of http://localhost:9000

**Comment by thepiwo** [comment]
good job, this seems to work for me :)

**Pull request merged**
