### PR TITLE
initial config for gh actions

### PR DESCRIPTION
**Pull request by mmpetarpeshev**
Migrate the build to gh actions.

### CODE REVIEW

**Review by dincho — APPROVED** [review]

**Comment by dincho** [comment]
What about current travis builds ?

**Comment by dincho** [comment]
Ah it's just GH config, let me drop it

**Comment by dincho** [comment]
hmm, nope the builds still seems to not be migrated to anything else than travis, maybe unrelated to this one

**Comment by davidyuk** [comment]
@mmpetarpeshev Any estimate on fixing ci or maybe you could revert changes made? As I know it was working ok before

**Comment by mmpetarpeshev** [comment]
> @mmpetarpeshev Any estimate on fixing ci or maybe you could revert changes made? As I know it was working ok before

We was in situation of what we gone use as build system . Let me check what is the situation , who is owner of the app ? 
If we gone use gh actions , I can merge my PR and add any steps , which are required.

**Comment by mmpetarpeshev** [comment]
> > Who is the owner of the app ?
> 
> I don't know, but I'm kind of a primary maintainer.
> 
> > The circle ci is still working , we didn't stop it
> 
> The thing is that we had per-branch tests and deployment running in CI, currently, I don't see a status reported for PRs I made.
> 
> > We have to sync are we going to migrate to gh actions.
> 
> I'm personally was fine with the Travis integration we had before.

I wrote you private message in slack , please take a look .Travic endpoint  is deprecated and we decided to not support automated deployments for now.

**Comment by marc0olo** [comment]
@mmpetarpeshev as travis is deprecated and we don't use it any longer let's use gh actions and make sure that the same jobs are covered.

not sure why this discussion was a problem in the past. sorry, didn't follow it.

the only thing I don't know is the circleci stuff. is it needed here? maybe @davidyuk or @CedrikNikita know that.

afaik we don't track circleci stuff on aepp and tooling side

**Pull request merged**
