### PR TITLE
Encrypt desktop-mobile connection using Noise Protocol Framework

### PR DESCRIPTION
**Pull request by davidyuk**
This PR depends on changes in `noise-c.wasm` package:
https://github.com/nazar-pc/noise-c.wasm/pull/2
https://github.com/nazar-pc/noise-c.wasm/pull/3

### CODE REVIEW

**Comment by davidyuk** [comment]
No, it is done. This PR introduces some crypto stuff and I'm waiting until Emil ask somebody to review it.

**Comment by j28** [comment]
has this been merged?

**Comment by j28** [comment]
@davidyuk what is the current status of this? who could review it?

**Comment by davidyuk** [comment]
Technically stuff in this PR works. We had an agreement to merge it after #222 because these changes may make more complicated developing of desktop-mobile connection. But now, I'm not sure about this decision. Maybe it is a good idea to rebase and merge it currently.

**Comment by etharner** [comment]
Too outdated for current architecture, i'm closing it.

**Pull request closed without merging**
