### PR TITLE
Improve Ledger UX

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by j28** [comment]
fixes confirmation prompt appearing continuously after confirmation.

**Comment by j28** [comment]
test script:
+ connect ledger
+ connect mobile with desktop
+ connect 2nd ledger
+ try to make transaction with first
+ decline transaction confirmation on ledger device

**Comment by davidyuk** [comment]
relater to #593

**Comment by CedrikNikita** [comment]
closes #640

**Pull request merged**
